name: Build-Test-Deploy

on:
  push:
    branches:
      - master

jobs:
 Build-Job:
     runs-on: Ubuntu-latest
     name: Pre requsite
     steps:
       -uses: actions/checkout@v1
       -name: Install surge
        uses: actions/setup-node@v1
        with: 
          node-version: 14
      -run: npm install -g surge
